# TEST-only collector profile. The base file is created by the pinned PG17 image.
include = '/var/lib/postgresql/data/postgresql.conf'

logging_collector = on
log_destination = 'jsonlog'
lc_messages = 'C'
log_error_verbosity = 'verbose'
log_min_messages = 'error'
log_min_error_statement = 'error'
log_statement = 'none'
log_duration = off
log_min_duration_statement = -1
log_min_duration_sample = -1
log_transaction_sample_rate = 0
log_parameter_max_length = 0
log_parameter_max_length_on_error = 0
log_truncate_on_rotation = off
log_directory = '/var/log/vra-poc04-collector'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_file_mode = 0640
log_rotation_age = '1d'
log_rotation_size = 0
